### ISSUE TITLE
Capture `tsserver` Chromium trace files in synthetic benchmarks

### ISSUE THREAD

**Issue by kitten** [0no-co/gql.tada#108]
In a local instance of `tsserver` it's possible to capture a Chromium trace file by setting `TSS_TRACE=__trace` as an environment variable. This outputs trace files to a `__trace` folder which can be inspected in the `chrome://tracing` tab.

However, in our synthetic benchmarks we currently don't have this capability. This would however be useful to immediately check the performance traces in our benchmarks for issues.

## Task

- [ ] Add toggle to output a trace file to our synthetic TS instance
- [ ] Add reproduction for #89 to a synthetic test
- [ ] Potentially run the above separately from `vitest bench` so it's not run repeatedly (which could be slow)
